/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely"

export type ArrayType<T> =
  ArrayTypeImpl<T> extends (infer U)[] ? U[] : ArrayTypeImpl<T>

export type ArrayTypeImpl<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S[], I[], U[]>
    : T[]

export type HealthFlag = "active" | "archived" | "drowning" | "inactive"

export type Timestamp = ColumnType<Date, Date | string, Date | string>

export interface Bookmark {
  name: string
  note: string | null
  owner: string
  userId: string
}

export interface Repository {
  archived: boolean
  createdAt: Timestamp
  description: string | null
  fullName: string
  githubCreatedAt: Timestamp
  githubUpdatedAt: Timestamp
  healthFlags: ArrayType<HealthFlag>
  homepageUrl: string | null
  htmlUrl: string
  language: string | null
  lastCommitAt: Timestamp | null
  latestRelease: string | null
  name: string
  openIssuesCount: number
  owner: string
  starsCount: number
  topics: string[]
  updatedAt: Timestamp
}

export interface User {
  githubToken: string | null
  id: string
}

export interface DB {
  bookmark: Bookmark
  repository: Repository
  user: User
}
